version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/node:14.18
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependancies-
            - v1-dependancies-
      - run:
          name: change npm location
          command: |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
            source ~/.profile
      - run:
          name: Install serverless content
          command: npm install serverless
      - run: 
          name: Install artifacts
          command: npm install
        
      - save_cache:
          paths:
            - node_modules
          key: v1-dependancies-

      - run:
          name: Depoly application
          command: serverless deploy --stage pre